global:
  scrape_interval: 5s

scrape_configs:
- job_name: radicle-registry-nodes
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names: [devnet]
  relabel_configs:
  # Only keep pods with the "pometheus_port" annotation
  - source_labels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_port]
    regex: "true"
    action: keep

  # Drop init containers
  - source_labels: [__meta_kubernetes_pod_container_init]
    regex: "true"
    action: drop

  # Use the "prometheus_port" annotation as the address
  - source_labels: [__meta_kubernetes_pod_ip,__meta_kubernetes_pod_annotation_prometheus_io_port]
    regex: ([^;]+);(\d+)
    replacement: $1:$2
    target_label: __address__

  # Set instance label
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: instance

  # Promote kubernetes discovery labels
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  - source_labels: [__meta_kubernetes_pod_container_name]
    action: replace
    target_label: kubernetes_pod_container_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: kubernetes_pod_label_$1
