unstable_features = true

max_width = 100
comment_width = 80
hard_tabs = false
tab_spaces = 4
wrap_comments = true

binop_separator = "Front"

condense_wildcard_suffixes = true

edition = "2018"

fn_single_line = true

format_code_in_doc_comments = true
format_strings = true

imports_indent = "Block"
imports_layout = "HorizontalVertical"

inline_attribute_width = 50

match_block_trailing_comma = true

merge_imports = true

newline_style = "Unix"

normalize_comments = true
normalize_doc_attributes = true

reorder_impl_items = true

use_field_init_shorthand = true

use_try_shorthand = true
