creation_rules:
- path_regex: buildkite-hooks/.*
  gcp_kms: projects/opensourcecoin/locations/global/keyRings/buildkite/cryptoKeys/service
- path_regex: linux/.*
  gcp_kms: projects/opensourcecoin/locations/global/keyRings/buildkite/cryptoKeys/bootstrap
- path_regex: .*/registry/.*
  gcp_kms: projects/radicle-registry-dev/locations/global/keyRings/dev/cryptoKeys/radicle-infra-repo
