creation_rules:
- path_regex: buildkite-hooks/.*
  gcp_kms: projects/opensourcecoin/locations/global/keyRings/buildkite/cryptoKeys/service
- path_regex: linux/.*
  gcp_kms: projects/opensourcecoin/locations/global/keyRings/buildkite/cryptoKeys/bootstrap
