env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build@sha256:4b87096dc84644ef1dc8b122862aae3be5cc04c54d25003b195051585b77c406"
  DOCKER_FILE: .docker/rust/Dockerfile

steps:
- label: "buildkite-hooks"
  command: .buildkite/build-buildkite-hooks.sh
  artifact_paths:
  - buildkite-hooks/target/debian/*.deb
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build"
    DOCKER_FILE: .docker/rust/Dockerfile
