env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build@sha256:0c453a56f4742ae03ef18f23fe2b45bb923d2737f5b547285818ddf5ca25af19"
  DOCKER_FILE: .docker/rust/Dockerfile

steps:
- label: "buildkite-hooks"
  command: .buildkite/build-buildkite-hooks.sh
  artifact_paths:
  - buildkite-hooks/target/debian/*.deb
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build"
    DOCKER_FILE: .docker/rust/Dockerfile
