env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build@sha256:68ad1974a73a0813d89f4b43f29be0005f3217448e46a7025073833547ca2bc8"
  DOCKER_FILE: .docker/rust/Dockerfile

steps:
- label: "buildkite-hooks"
  command: .buildkite/build-buildkite-hooks.sh
  artifact_paths:
  - buildkite-hooks/target/debian/*.deb
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build"
    DOCKER_FILE: .docker/rust/Dockerfile
