steps:
- label: "zockervols: Build + Test"
  command: "cargo test --all"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/zockervols-build@sha256:3713b2adf81c7b73eb9ec3dc357cb99327b40fa5efc481d4ad021a7cd4d4fe84"
    DOCKER_FILE: .docker/rust/Dockerfile

- label: "zockervols: Package"
  command: ".buildkite/package-zockervols.sh"
  branches: "master"
  artifact_paths:
  - artifacts/*
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/zockervols-build@sha256:3713b2adf81c7b73eb9ec3dc357cb99327b40fa5efc481d4ad021a7cd4d4fe84"
    DOCKER_FILE: .docker/rust/Dockerfile
  # Temporary measure while Bintray account is locked
  soft_fail:
  - exit_status: 22

- label: "buildkite-hooks"
  command: .buildkite/build-buildkite-hooks.sh
  artifact_paths:
  - artifacts/*
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build@sha256:30f5c169d200228448ca497c81bddc089a82867ba4b29732d2d5ba78a3d8e180"
    DOCKER_FILE: .docker/rust/Dockerfile

- label: "buildkite-hooks-agent-preview"
  command: .buildkite/build-buildkite-hooks.sh
  artifact_paths:
  - artifacts/*
  agents:
    queue: agent-preview
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build@sha256:30f5c169d200228448ca497c81bddc089a82867ba4b29732d2d5ba78a3d8e180"
    DOCKER_FILE: .docker/rust/Dockerfile
