
steps:
- label: "zockervols: Build + Test"
  command: "cargo test --all"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/zockervols-build@sha256:4b87096dc84644ef1dc8b122862aae3be5cc04c54d25003b195051585b77c406"
    DOCKER_FILE: .docker/rust/Dockerfile

- label: "zockervols: Package"
  command: ".buildkite/package-zockervols.sh"
  branches: "master"
  artifact_paths:
  - "zockervols/target/debian/*.deb"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/zockervols-build@sha256:4b87096dc84644ef1dc8b122862aae3be5cc04c54d25003b195051585b77c406"
    DOCKER_FILE: .docker/rust/Dockerfile
  # Temporary measure while Bintray account is locked
  soft_fail:
  - exit_status: 22
