env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build@sha256:6bd0bdaaf39375d10bffae5dd7306546b152b7daa88258273b2d70972fac3b3e"
  DOCKER_FILE: .docker/rust/Dockerfile

steps:
- label: "buildkite-hooks"
  command: .buildkite/build-buildkite-hooks.sh
  artifact_paths:
  - buildkite-hooks/target/debian/*.deb
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/buildkite-hooks-build"
    DOCKER_FILE: .docker/rust/Dockerfile
