
steps:
- label: "zockervols: Build + Test"
  command: "cargo test --all"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/zockervols-build@sha256:612efe3e4a78cd82d0169538ab6bfea794afae0165a76e1bd287923f54807a31"
    DOCKER_FILE: .docker/build/Dockerfile

- label: "zockervols: Package"
  command: ".buildkite/package-zockervols.sh"
  branches: "master"
  artifact_paths:
  - "zockervols/target/debian/*.deb"
  agents:
    production: "true"
    platform: "linux"
  env:
    DOCKER_IMAGE: "gcr.io/opensourcecoin/zockervols-build@sha256:612efe3e4a78cd82d0169538ab6bfea794afae0165a76e1bd287923f54807a31"
    DOCKER_FILE: .docker/build/Dockerfile
